# Generated by Django 5.2.14 on 2026-07-16 12:19

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_DEPARTMENT_NAME = "General department"


def create_default_departments(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Department = apps.get_model("organizations", "Department")
    OrganizationMember = apps.get_model("organizations", "OrganizationMember")

    for organization in Organization.objects.all():
        department, _ = Department.objects.get_or_create(
            organization=organization,
            name=DEFAULT_DEPARTMENT_NAME,
            defaults={"is_active": True},
        )
        OrganizationMember.objects.filter(
            organization=organization,
            department__isnull=True,
        ).update(department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.department'),
        ),
        migrations.RunPython(create_default_departments, migrations.RunPython.noop),
    ]
