# Generated by Django 5.2.14 on 2026-07-28 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0014_alter_templatepartyfield_field_type_money'),
        ('organizations', '0002_department_organizationmember_department'),
        ('signing', '0005_signer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission API client',
                'verbose_name_plural': 'Admission API clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionTemplateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('education_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('other', 'Other')], db_index=True, default='bachelor', max_length=30)),
                ('funding_type', models.CharField(choices=[('paid', 'Paid'), ('grant', 'Grant'), ('other', 'Other')], db_index=True, default='paid', max_length=30)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('kk', 'Kazakh'), ('en', 'English'), ('any', 'Any')], db_index=True, default='any', max_length=10)),
                ('program_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_template_rules', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': 'Admission template rule',
                'verbose_name_plural': 'Admission template rules',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('access_token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('education_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('other', 'Other')], db_index=True, default='bachelor', max_length=30)),
                ('funding_type', models.CharField(choices=[('paid', 'Paid'), ('grant', 'Grant'), ('other', 'Other')], db_index=True, default='paid', max_length=30)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('kk', 'Kazakh'), ('en', 'English'), ('any', 'Any')], db_index=True, default='ru', max_length=10)),
                ('program_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('program_name_ru', models.CharField(blank=True, max_length=255)),
                ('program_name_kk', models.CharField(blank=True, max_length=255)),
                ('applicant_full_name', models.CharField(max_length=255)),
                ('applicant_iin', models.CharField(db_index=True, max_length=12)),
                ('applicant_phone', models.CharField(max_length=30)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('tuition_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('document_created', 'Document created'), ('student_signing', 'Waiting for student signature'), ('student_signed', 'Student signed'), ('vice_rector_pending', 'Waiting for vice rector'), ('vice_rector_signed', 'Vice rector signed'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='received', max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='admissions.admissionapiclient')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_contracts', to='documents.document')),
                ('student_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_admission_contracts', to='signing.signer')),
                ('vice_rector_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_rector_admission_contracts', to='signing.signer')),
                ('template_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='admissions.admissiontemplaterule')),
            ],
            options={
                'verbose_name': 'Admission contract',
                'verbose_name_plural': 'Admission contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionViceRectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_vice_rectors', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_vice_rectors', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_vice_rector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission vice rector profile',
                'verbose_name_plural': 'Admission vice rector profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='admissiontemplaterule',
            name='vice_rector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_rules', to='admissions.admissionvicerectorprofile'),
        ),
    ]
