# Generated by Django 5.2.14 on 2026-07-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncontract',
            name='education_level',
            field=models.CharField(choices=[('any', 'Any'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('other', 'Other')], db_index=True, default='bachelor', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissiontemplaterule',
            name='education_level',
            field=models.CharField(choices=[('any', 'Any'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('other', 'Other')], db_index=True, default='bachelor', max_length=30),
        ),
    ]
