# Generated by Django 5.2.14 on 2026-07-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_admissioncontract_education_level_and_more'),
        ('documents', '0014_alter_templatepartyfield_field_type_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncontract',
            name='application_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='documents.document'),
        ),
        migrations.AddField(
            model_name='admissiontemplaterule',
            name='application_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_application_template_rules', to='documents.documenttemplate'),
        ),
    ]
