# Generated by Django 5.2.14 on 2026-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissioncontract_application_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionMssqlContractRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('admission_contract_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('document_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('application_document_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('student_signer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('vice_rector_signer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('api_client_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('api_client_name', models.CharField(blank=True, max_length=255)),
                ('template_rule_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, db_index=True, max_length=30)),
                ('funding_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('language', models.CharField(blank=True, db_index=True, max_length=10)),
                ('program_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('program_name_ru', models.CharField(blank=True, max_length=255)),
                ('program_name_kk', models.CharField(blank=True, max_length=255)),
                ('applicant_full_name', models.CharField(blank=True, max_length=255)),
                ('applicant_iin', models.CharField(blank=True, db_index=True, max_length=12)),
                ('applicant_phone', models.CharField(blank=True, max_length=30)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('tuition_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=40)),
                ('public_url', models.TextField(blank=True)),
                ('raw_payload_json', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Admission MSSQL contract record',
                'verbose_name_plural': 'Admission MSSQL contract records',
                'db_table': 'admission_contract_records',
                'ordering': ['-synced_at'],
            },
        ),
    ]
