# Generated by Django 5.2.14 on 2026-06-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Document becomes locked after signer invitation', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rendered_docx_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/docx/'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='field_schema',
            field=models.JSONField(blank=True, default=list, help_text='Groups and fields for document form editor'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='document_templates/docx/'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the final document content', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting_for_signers', 'Waiting for signers'), ('partially_signed', 'Partially signed'), ('signed', 'Signed'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='body_template',
            field=models.TextField(blank=True, help_text='Use variables like {{ client_name }}, {{ amount }}'),
        ),
        migrations.CreateModel(
            name='TemplateParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('variable_prefix', models.SlugField(max_length=100)),
                ('party_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=30)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('is_signer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['signing_order', 'id'],
                'unique_together': {('template', 'variable_prefix')},
            },
        ),
        migrations.CreateModel(
            name='TemplatePartyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('variable_name', models.SlugField(help_text='Example: full_name, iin_bin, phone, address, iban', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('phone', 'Phone'), ('iin_bin', 'IIN / BIN'), ('signing_method', 'Signing method'), ('email', 'Email'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System fields are required for signing logic')),
                ('order', models.PositiveIntegerField(default=1)),
                ('default_value', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.templateparty')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('party', 'variable_name')},
            },
        ),
    ]
