# Generated by Django 5.2.14 on 2026-06-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_locked_at_document_rendered_docx_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='document_templates/files/'),
        ),
    ]
