# Generated by Django 5.2.14 on 2026-06-14 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_documenttemplate_overlay_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLawVisionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manager', 'Manager'), ('public_signer', 'Public signer')], default='manager', max_length=30)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('language', models.CharField(default='ru', max_length=5)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('perspective', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('contract_type_detected', models.CharField(blank=True, max_length=100)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawvision_reports', to='documents.document')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawvision_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LawVision report',
                'verbose_name_plural': 'LawVision reports',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'content_hash', 'language', 'contract_type', 'perspective'), name='uniq_lawvision_doc_hash_options')],
            },
        ),
    ]
