# Generated by Django 5.2.14 on 2026-06-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentlawvisionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('final_pdf', 'Final PDF'), ('final_docx', 'Final DOCX'), ('signature', 'Signature'), ('evidence_bundle', 'Evidence bundle'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('version_id', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('retention_mode', models.CharField(choices=[('COMPLIANCE', 'Compliance'), ('GOVERNANCE', 'Governance'), ('NONE', 'None')], default='COMPLIANCE', max_length=20)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('storage_status', models.CharField(choices=[('stored', 'Stored'), ('failed', 'Failed')], db_index=True, default='stored', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_objects', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stored_objects', to='documents.document')),
            ],
            options={
                'verbose_name': 'Stored object',
                'verbose_name_plural': 'Stored objects',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='stored_object_sha256_hex'), models.UniqueConstraint(fields=('bucket', 'object_key', 'version_id'), name='uniq_stored_object_version')],
            },
        ),
    ]
