# Generated by Codex on 2026-06-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_storedobject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="documents.documenttemplate",
            ),
        ),
    ]
