# Generated by Django 5.2.14 on 2026-07-12 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_template_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLedgerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('actor', models.CharField(default='sign_app', max_length=100)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('ledger_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('document_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('entry_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('server_signature_b64', models.TextField(blank=True)),
                ('server_key_id', models.CharField(blank=True, max_length=255)),
                ('ledger_created_at', models.DateTimeField(blank=True, null=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_records', to='documents.document')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document ledger record',
                'verbose_name_plural': 'Document ledger records',
                'ordering': ['-created_at'],
            },
        ),
    ]
