# Generated by Django 5.2.14 on 2026-07-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentledgerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentledgerrecord',
            name='document_token',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentledgerrecord',
            name='last_verification_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentledgerrecord',
            name='last_verification_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentledgerrecord',
            name='last_verification_status',
            field=models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='documentledgerrecord',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentledgerrecord',
            name='ledger_pdf_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_records', to='documents.storedobject'),
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='object_type',
            field=models.CharField(choices=[('final_pdf', 'Final PDF'), ('final_docx', 'Final DOCX'), ('ledger_pdf', 'Ledger PDF'), ('signature', 'Signature'), ('evidence_bundle', 'Evidence bundle'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
    ]
