# Generated by Django 5.2.14 on 2026-07-15 06:31

from django.utils import timezone
from django.db import migrations, models


SIGNED_DOCUMENT_UPDATE_TRIGGER = "documents_document_no_signed_update"


def set_signed_document_update_trigger(schema_editor, *, enabled):
    if schema_editor.connection.vendor != "postgresql":
        return

    action = "ENABLE" if enabled else "DISABLE"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_trigger WHERE tgname = %s",
            [SIGNED_DOCUMENT_UPDATE_TRIGGER],
        )

        if cursor.fetchone():
            cursor.execute(
                f"ALTER TABLE documents_document {action} TRIGGER {SIGNED_DOCUMENT_UPDATE_TRIGGER}"
            )


def populate_contract_identity(apps, schema_editor):
    Document = apps.get_model("documents", "Document")

    set_signed_document_update_trigger(schema_editor, enabled=False)

    try:
        for document in Document.objects.order_by("id"):
            contract_date = document.contract_date

            if not contract_date:
                if document.created_at:
                    contract_date = timezone.localtime(document.created_at).date()
                else:
                    contract_date = timezone.localdate()

            contract_number = document.contract_number or f"{contract_date.year}-{document.pk:06d}"

            Document.objects.filter(pk=document.pk).update(
                contract_date=contract_date,
                contract_number=contract_number,
            )
    finally:
        set_signed_document_update_trigger(schema_editor, enabled=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentledgerrecord_document_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract_date',
            field=models.DateField(blank=True, db_index=True, help_text='Contract composition date generated when the document is created.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique contract number generated when the document is created.', max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(populate_contract_identity, noop_reverse),
    ]
