# Generated by Django 5.2.14 on 2026-07-16 12:19

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_DEPARTMENT_NAME = "General department"


def get_default_department(Department, organization_id):
    department = (
        Department.objects
        .filter(organization_id=organization_id, name=DEFAULT_DEPARTMENT_NAME)
        .first()
    )

    if department:
        return department

    return Department.objects.create(
        organization_id=organization_id,
        name=DEFAULT_DEPARTMENT_NAME,
        is_active=True,
    )


def assign_existing_records_to_default_department(apps, schema_editor):
    Department = apps.get_model("organizations", "Department")
    Document = apps.get_model("documents", "Document")
    DocumentTemplate = apps.get_model("documents", "DocumentTemplate")

    for template in DocumentTemplate.objects.filter(department__isnull=True):
        department = get_default_department(Department, template.organization_id)
        template.department_id = department.id
        template.save(update_fields=["department"])

    document_table = schema_editor.connection.ops.quote_name(Document._meta.db_table)

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {document_table} DISABLE TRIGGER USER")

    try:
        for document in Document.objects.filter(department__isnull=True):
            department_id = None

            if document.template_id:
                template = DocumentTemplate.objects.filter(pk=document.template_id).first()
                if template and template.department_id:
                    department_id = template.department_id

            if not department_id:
                department = get_default_department(Department, document.organization_id)
                department_id = department.id

            Document.objects.filter(pk=document.pk).update(department_id=department_id)
    finally:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE {document_table} ENABLE TRIGGER USER")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_verification_token'),
        ('organizations', '0002_department_organizationmember_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='organizations.department'),
        ),
        migrations.RunPython(
            assign_existing_records_to_default_department,
            migrations.RunPython.noop,
        ),
    ]
