"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()


#настройки mobizon
SMS_BACKEND = os.getenv("SMS_BACKEND", "console")
SMS_TIMEOUT_SECONDS = int(os.getenv("SMS_TIMEOUT_SECONDS", "10"))

MOBIZON_API_URL = os.getenv("MOBIZON_API_URL", "https://api.mobizon.kz/service")
MOBIZON_API_KEY = os.getenv("MOBIZON_API_KEY", "")
MOBIZON_SENDER = os.getenv("MOBIZON_SENDER", "")

#LawVision
LAWVISION_API_KEY = os.getenv("LAWVISION_API_KEY", "")
LAWVISION_API_URL = os.getenv("LAWVISION_API_URL", "https://lawvision.kz/api/v1")
LAWVISION_TIMEOUT_SECONDS = int(os.getenv("LAWVISION_TIMEOUT_SECONDS", "90"))

# Sign ledger integration
LEDGER_ENABLED = os.getenv("LEDGER_ENABLED", "False").lower() in {"1", "true", "yes", "on"}
LEDGER_API_URL = os.getenv("LEDGER_API_URL", "https://blockchain.kaznu.kz/v1")
LEDGER_API_KEY_FILE = os.getenv("LEDGER_API_KEY_FILE", "/etc/sign-ledger-client/api-key")
LEDGER_CA_CERT_FILE = os.getenv("LEDGER_CA_CERT_FILE", "")
LEDGER_CLIENT_CERT_FILE = os.getenv("LEDGER_CLIENT_CERT_FILE", "/etc/sign-ledger-client/client.crt")
LEDGER_CLIENT_KEY_FILE = os.getenv("LEDGER_CLIENT_KEY_FILE", "/etc/sign-ledger-client/client.key")
LEDGER_TIMEOUT_SECONDS = int(os.getenv("LEDGER_TIMEOUT_SECONDS", "60"))
LEDGER_ACTOR = os.getenv("LEDGER_ACTOR", "sign_app")
LEDGER_EXTERNAL_ID_PREFIX = os.getenv("LEDGER_EXTERNAL_ID_PREFIX", "contract")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-c#%6#jnn$-rzu814j1javkw0am!)hl)r3@57x0b5)_@t-vp$!u",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    "False",
).lower() in {"1", "true", "yes", "on"}
SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Third-party
    "rest_framework",

    #Local apps
    "accounts",
    "organizations",
    "documents.apps.DocumentsConfig",
    "signing",
    "admissions.apps.AdmissionsConfig",
    "providers",
    "notifications",
    "audit",
    "core",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'organizations.context_processors.organization_access',
                'admissions.context_processors.admissions_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "sign_app"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": int(os.getenv("POSTGRES_CONN_MAX_AGE", "60")),
    }
}

POSTGRES_SSLMODE = os.getenv("POSTGRES_SSLMODE")
if POSTGRES_SSLMODE:
    DATABASES["default"]["OPTIONS"] = {"sslmode": POSTGRES_SSLMODE}

ADMISSIONS_MSSQL_ENABLED = os.getenv("ADMISSIONS_MSSQL_ENABLED", "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
ADMISSIONS_MSSQL_REQUIRED = os.getenv("ADMISSIONS_MSSQL_REQUIRED", "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
ADMISSIONS_ASYNC_RENDER_ENABLED = os.getenv(
    "ADMISSIONS_ASYNC_RENDER_ENABLED",
    "False",
).lower() in {
    "1",
    "true",
    "yes",
    "on",
}
if ADMISSIONS_MSSQL_ENABLED:
    DATABASES["admissions_mssql"] = {
        "ENGINE": os.getenv("ADMISSIONS_MSSQL_ENGINE", "mssql"),
        "NAME": os.getenv("ADMISSIONS_MSSQL_NAME", ""),
        "USER": os.getenv("ADMISSIONS_MSSQL_USER", ""),
        "PASSWORD": os.getenv("ADMISSIONS_MSSQL_PASSWORD", ""),
        "HOST": os.getenv("ADMISSIONS_MSSQL_HOST", ""),
        "PORT": os.getenv("ADMISSIONS_MSSQL_PORT", "1433"),
        "OPTIONS": {
            "driver": os.getenv("ADMISSIONS_MSSQL_DRIVER", "ODBC Driver 18 for SQL Server"),
            "extra_params": os.getenv("ADMISSIONS_MSSQL_EXTRA_PARAMS", ""),
        },
    }

DATABASE_ROUTERS = ["config.database_routers.AdmissionsMssqlRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
    ("kk", "Қазақша"),
]


LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

LIBREOFFICE_PATH = os.getenv("LIBREOFFICE_PATH", "")
PDF_OVERLAY_FONT_PATH = os.getenv("PDF_OVERLAY_FONT_PATH", "")
PUBLIC_SITE_URL = os.getenv("PUBLIC_SITE_URL", "")


# Immutable object storage for final legal documents and evidence.
MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "127.0.0.1:9000")
MINIO_EXTERNAL_ENDPOINT = os.getenv("MINIO_EXTERNAL_ENDPOINT", "http://127.0.0.1:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "signappminio")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "signappminio123")
MINIO_BUCKET = os.getenv("MINIO_BUCKET", "sign-app-documents")
MINIO_SECURE = os.getenv("MINIO_SECURE", "False").lower() in {"1", "true", "yes", "on"}
MINIO_DEFAULT_RETENTION_DAYS = int(os.getenv("MINIO_DEFAULT_RETENTION_DAYS", "30"))
OBJECT_STORAGE_ENABLED = os.getenv("OBJECT_STORAGE_ENABLED", "True").lower() in {"1", "true", "yes", "on"}


#ECP verifier
ECP_VERIFIER_URL = os.getenv("ECP_VERIFIER_URL", "http://127.0.0.1:9001/verify-ecp")


# ONLYOFFICE Docs integration. The browser loads scripts from
# ONLYOFFICE_SERVER_URL, while Document Server uses ONLYOFFICE_DJANGO_URL to
# download documents and send save callbacks back to Django.
ONLYOFFICE_SERVER_URL = os.getenv("ONLYOFFICE_SERVER_URL", "http://127.0.0.1:8082")
ONLYOFFICE_COMMAND_SERVICE_URL = os.getenv(
    "ONLYOFFICE_COMMAND_SERVICE_URL",
    f"{ONLYOFFICE_SERVER_URL.rstrip('/')}/command",
)
ONLYOFFICE_DJANGO_URL = os.getenv("ONLYOFFICE_DJANGO_URL", "http://host.docker.internal:8000")
ONLYOFFICE_JWT_SECRET = os.getenv("ONLYOFFICE_JWT_SECRET", SECRET_KEY)
ONLYOFFICE_JWT_HEADER = os.getenv("ONLYOFFICE_JWT_HEADER", "Authorization")
ONLYOFFICE_ACCESS_TOKEN_TTL_SECONDS = int(os.getenv("ONLYOFFICE_ACCESS_TOKEN_TTL_SECONDS", "86400"))


DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
ADMISSIONS_LOG_LEVEL = os.getenv("ADMISSIONS_LOG_LEVEL", DJANGO_LOG_LEVEL).upper()
DJANGO_LOG_FILE = os.getenv("DJANGO_LOG_FILE", "").strip()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "admissions": {
            "handlers": ["console"],
            "level": ADMISSIONS_LOG_LEVEL,
            "propagate": False,
        },
    },
}

if DJANGO_LOG_FILE:
    LOGGING["handlers"]["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "formatter": "standard",
        "filename": DJANGO_LOG_FILE,
        "maxBytes": 10 * 1024 * 1024,
        "backupCount": 5,
        "encoding": "utf-8",
    }
    LOGGING["root"]["handlers"].append("file")
    for logger_settings in LOGGING["loggers"].values():
        logger_settings["handlers"].append("file")
