# Generated by Django 5.2.14 on 2026-05-16 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(db_index=True, max_length=12)),
                ('phone', models.CharField(max_length=30)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sms_sent', 'SMS sent'), ('opened', 'Opened'), ('signing_started', 'Signing started'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.document')),
            ],
            options={
                'verbose_name': 'Signer',
                'verbose_name_plural': 'Signers',
                'ordering': ['signing_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignerAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='signing.signer')),
            ],
            options={
                'verbose_name': 'Signer access token',
                'verbose_name_plural': 'Signer access tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('egov_mobile', 'eGov Mobile'), ('mock', 'Mock')], default='mock', max_length=50)),
                ('provider_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting'), ('signed', 'Signed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='created', max_length=30)),
                ('deep_link', models.TextField(blank=True)),
                ('qr_payload', models.TextField(blank=True)),
                ('document_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='signing.signer')),
            ],
            options={
                'verbose_name': 'Signing session',
                'verbose_name_plural': 'Signing sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('certificate_iin', models.CharField(db_index=True, max_length=12)),
                ('certificate_subject', models.TextField(blank=True)),
                ('certificate_serial', models.CharField(blank=True, max_length=255)),
                ('signature_value', models.TextField(blank=True)),
                ('signed_content_hash', models.CharField(db_index=True, max_length=64)),
                ('signed_at', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_error', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
                ('signer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='signing.signer')),
                ('signing_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='signing.signingsession')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
