# Generated by Django 5.2.14 on 2026-06-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_locked_at_document_rendered_docx_file_and_more'),
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='confirmation_text',
            field=models.TextField(blank=True, help_text='Human-readable signing confirmation sheet text'),
        ),
        migrations.AddField(
            model_name='signature',
            name='consent_text',
            field=models.TextField(blank=True, help_text='Text of consent accepted by signer before SMS signing'),
        ),
        migrations.AddField(
            model_name='signature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='role_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='signer',
            name='signing_method',
            field=models.CharField(choices=[('egov_mobile', 'eGov Mobile'), ('sms', 'SMS confirmation'), ('ecp', 'ЭЦП')], default='egov_mobile', max_length=32),
        ),
        migrations.AddField(
            model_name='signer',
            name='template_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signers', to='documents.templateparty'),
        ),
        migrations.AddField(
            model_name='signingsession',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signingsession',
            name='code_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of SMS code', max_length=64),
        ),
        migrations.AddField(
            model_name='signingsession',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingsession',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='signingsession',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='certificate_iin',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='signature',
            name='provider',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sms_sent', 'SMS sent'), ('opened', 'Opened'), ('signing_started', 'Signing started'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='signingsession',
            name='provider',
            field=models.CharField(choices=[('egov_mobile', 'eGov Mobile'), ('mock', 'Mock'), ('sms', 'SMS confirmation'), ('ecp', 'ЭЦП')], db_index=True, default='mock', max_length=50),
        ),
        migrations.AlterField(
            model_name='signingsession',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting'), ('code_sent', 'Code sent'), ('signed', 'Signed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('used', 'Used')], db_index=True, default='created', max_length=30),
        ),
        migrations.CreateModel(
            name='SigningAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('signer_added', 'Signer added'), ('document_locked', 'Document locked'), ('document_hash_fixed', 'Document hash fixed'), ('access_link_created', 'Access link created'), ('invitation_sms_sent', 'Invitation SMS sent'), ('link_opened', 'Link opened'), ('egov_session_started', 'eGov Mobile session started'), ('ecp_signing_started', 'ECP signing started'), ('ecp_signature_received', 'ECP signature received'), ('ecp_signature_validated', 'ECP signature validated'), ('ecp_signature_invalid', 'ECP signature invalid'), ('sms_consent_accepted', 'SMS consent accepted'), ('sms_code_requested', 'SMS code requested'), ('sms_code_sent', 'SMS code sent'), ('sms_code_failed', 'SMS code failed'), ('sms_code_invalid', 'SMS code invalid'), ('sms_code_expired', 'SMS code expired'), ('sms_code_cooldown', 'SMS code cooldown'), ('sms_code_attempts_exceeded', 'SMS code attempts exceeded'), ('sms_code_confirmed', 'SMS code confirmed'), ('signature_created', 'Signature created'), ('document_signed', 'Document signed'), ('status_recalculated', 'Status recalculated'), ('repeat_sign_blocked', 'Repeat signing blocked'), ('signing_failed', 'Signing failed')], db_index=True, max_length=64)),
                ('signing_method', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('iin', models.CharField(blank=True, max_length=12)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('document_hash', models.CharField(blank=True, max_length=128)),
                ('signed_content_hash', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_audit_logs', to='documents.document')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_audit_logs', to='signing.signer')),
                ('signing_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_audit_logs', to='signing.signingsession')),
            ],
            options={
                'verbose_name': 'Signing audit log',
                'verbose_name_plural': 'Signing audit logs',
                'ordering': ['created_at'],
            },
        ),
    ]
