# Generated by Django 5.2.14 on 2026-06-15 08:02

import hashlib
import json

from django.db import migrations, models


def canonical_json(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def calculate_payload_hash(metadata):
    payload = canonical_json(metadata or {})
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def calculate_entry_hash(log, payload_hash, previous_hash):
    payload = {
        "document_id": log.document_id,
        "signer_id": log.signer_id,
        "signing_session_id": log.signing_session_id,
        "event": log.event,
        "signing_method": log.signing_method,
        "phone": log.phone,
        "iin": log.iin,
        "full_name": log.full_name,
        "ip_address": str(log.ip_address or ""),
        "user_agent": log.user_agent,
        "document_hash": log.document_hash,
        "signed_content_hash": log.signed_content_hash,
        "payload_hash": payload_hash,
        "previous_hash": previous_hash,
    }
    canonical = canonical_json(payload)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def backfill_hash_chain(apps, schema_editor):
    SigningAuditLog = apps.get_model("signing", "SigningAuditLog")

    previous_by_document = {}

    for log in SigningAuditLog.objects.order_by("document_id", "id"):
        previous_hash = previous_by_document.get(log.document_id, "")
        payload_hash = calculate_payload_hash(log.metadata)
        entry_hash = calculate_entry_hash(log, payload_hash, previous_hash)

        SigningAuditLog.objects.filter(pk=log.pk).update(
            previous_hash=previous_hash,
            payload_hash=payload_hash,
            entry_hash=entry_hash,
        )

        previous_by_document[log.document_id] = entry_hash


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_signature_confirmation_text_signature_consent_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingauditlog',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signingauditlog',
            name='payload_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signingauditlog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_hash_chain, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='signingauditlog',
            name='entry_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION prevent_signing_audit_log_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'signing_signingauditlog is append-only';
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS signing_audit_log_no_update ON signing_signingauditlog;
            CREATE TRIGGER signing_audit_log_no_update
            BEFORE UPDATE ON signing_signingauditlog
            FOR EACH ROW EXECUTE FUNCTION prevent_signing_audit_log_mutation();

            DROP TRIGGER IF EXISTS signing_audit_log_no_delete ON signing_signingauditlog;
            CREATE TRIGGER signing_audit_log_no_delete
            BEFORE DELETE ON signing_signingauditlog
            FOR EACH ROW EXECUTE FUNCTION prevent_signing_audit_log_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS signing_audit_log_no_update ON signing_signingauditlog;
            DROP TRIGGER IF EXISTS signing_audit_log_no_delete ON signing_signingauditlog;
            DROP FUNCTION IF EXISTS prevent_signing_audit_log_mutation();
            """,
        ),
    ]
